### ISSUE TITLE
Publish on Conda

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/C-Star#49]

**Comment by NoraLoose** [comment]
To get `C-Star` on conda-forge, there a few steps that need to be done. I will start documenting them here:

### Setup (only necessary once)

Follow the constructions on https://github.com/conda-forge/staged-recipes
* fork https://github.com/conda-forge/staged-recipes
```
cd staged-recipes/recipes
```
   * after installing `grayskull` do
```
grayskull pypi cstar-ocean
```
which generates the following recipe:
```
{% set name = "cstar-ocean" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cstar_ocean-{{ version }}.tar.gz
  sha256: e61485b3ee34787f649638913db7519bc26cb7ac50ea56ecd2ec91e851646e9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0.0
    - wheel
    - setuptools-scm >=7.0
    - check-manifest
    - pip
  run:
    - python >=3.10
    - python-dateutil >=2.8.2
    - python-dotenv
    - pyyaml ==6.0.2
    - pooch >=1.8.1
    - roms-tools >=2.0.0

test:
  imports:
    - ci
    - cstar
    - dist
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Computational systems for tracking ocean carbon
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NoraLoose
```
which then needs to be manually modified.

* To allow multiple versions of `C-Star` on conda, let's look at [this example](https://github.com/conda-forge/cloudpathlib-feedstock/blob/main/recipe/meta.yaml) when modifying the recipe above.
